analisis preliminar v14

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -27,9 +27,6 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
-          #if [ "${{ github.ref_name }}" != "main" ]; then "El análisis de Sonar se ejecuta únicamente en la rama 'main'. Rama actual: ${{ github.ref_name }}"
-          #  exit 1
-          #fi
           npm install -g sonar-scanner
           sonar-scanner \
             -Dsonar.projectKey=${{ github.event.repository.name }} \
@@ -37,7 +34,23 @@ jobs:
             -Dsonar.sources=. \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.login=$SONAR_TOKEN
-            -Dsonar.branch.name=main
+            
+        - name: Validate Quality Gate
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          echo "Validating Quality Gate..."
+          analysisId=$(curl -s -u "$SONAR_TOKEN:" \
+            "https://sonarcloud.io/api/ce/component?component=${{ github.event.repository.name }}" | jq -r '.current.analysisId')
+
+          qualityGateStatus=$(curl -s -u "$SONAR_TOKEN:" \
+            "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$analysisId" | jq -r '.projectStatus.status')
+
+          if [ "$qualityGateStatus" != "OK" ]; then
+            echo "Quality Gate failed: $qualityGateStatus"
+            exit 1
+          fi
+
   SCA:
     needs: SAST
     runs-on: ubuntu-24.04
